config/routes.rb
Djsbestfriend::Application.routes.draw do

	resources :users do
		member do
			get :owned_records
		end
	end
	
	resources :sessions, :only => [:new, :create, :destroy]
	resources :records do
		member do
			get :owners
		end
	end
	
	resources :playlists do
		member do
			get :playlist_tracks
		end
	end
	
	resources :tracks do
		member do
			get :playlists
		end
	end
	
	resources :ownership_relationships, :only => [:create, :destroy]
	resources :playlist_relationships, :only => [:create, :destroy]
	
	match '/signup',  :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

	match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  root :to => 'pages#home'

end

app/models/record.rb
class Record < ActiveRecord::Base
	attr_accessible :title, :artist, :genre, :record_type, :year, :comment, :catalog_number, :tracks_attributes
	has_many :tracks, :dependent => :destroy
	accepts_nested_attributes_for :tracks
	
	has_many :ownership_relationships, :foreign_key => "owned_record_id",
													 :dependent => :destroy
	
	has_many :owners, :through => :ownership_relationships
		
	validates :title, :presence => true, :uniqueness => { :scope => :catalog_number }
	validates :artist, :presence => true
	validates :genre, :presence => true
	validates :record_type, :presence => true, :inclusion => { 
																			:in => ["12\"", "7\"", "10\"", "LP", "2xLP", "3xLP", "4xLP",
																							"Box"],
																			:message => "Select a valid type for your record." }
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
	
	def new
		@record = Record.new
	end

	def show
		@record = Record.find(params[:id])
		@title = @record.artist + " - " + @record.title
		@tracks = @record.tracks
	end
	
	def edit
		@record = Record.find(params[:id])
		@title = "Edit record"
	end
	
	def index
		@records = Record.paginate(:page => params[:page])
	end
	
	def create
    @record = Record.new(params[:record])
    if @record.save
			flash[:success] = "New record created!"
      redirect_to root_path
    else
      @title = "Add a new record"
      render 'new'
    end
  end
	
	def update
		@record = Record.find(params[:id])
		if @record.update_attributes(params[:record])
			flash[:success] = "Record updated."
			redirect_to @record
		else
			@title = "Edit record"
			render 'edit'
		end
	end
	
	def destroy
		if signed_in?
			@record = Record.find(params[:id])
			@record.destroy
			flash[:success] = "Record destroyed."
			redirect_to records_path
		else
			flash[:error] = "Please sign in to destroy a record."
			redirect_to signin_path
		end
	end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_fields.html.erb
<%= f.inputs do %>
	<%= f.input :title %>
	<%= f.input :artist %>
	<%= f.input :genre %>
	<%= f.input :record_type, :as => :select, :collection => ["12\"", "7\"", "10\"", 
																														"LP", "2xLP", "3xLP", "4xLP", "Box"], :include_blank => false %>  
	<%= f.input :year, :as => :date,		 :discard_day => true, :discard_month => true, :start_year => Time.now.year,
																			 :end_year => Time.now.year-70, :include_blank => false  %>
	<%= f.input :catalog_number %>
	<%= f.input :comment, :input_html => { :class => 'comment' } %>
<% end %>

app/views/records/_own.html.erb
<%= form_for current_user.reverse_ownership_relationships.
                          build(:owned_record_id => @record.id) do |f| %>
  <div><%= f.hidden_field :owned_record_id %></div>
  <div class="actions"><%= f.submit "Add to collection" %></div>
<% end %>

app/views/records/_own_form.html.erb
 <% unless current_user == @user || @record.nil? %>
	 <div id="own_form">
  <% if current_user.owning?(@record) %>
    <%= render 'records/stop_owning' %>
  <% else %>
    <%= render 'records/own' %>
  <% end %>
  </div>
<% end %>

app/views/records/_record.html.erb
<tr>
		<td class="artist">
		  <%= record.artist %>
		</td>
		<td class="title">
			 <%= link_to record.title, record %>
		</td>
		<td class="year">
			<%= record.year.strftime("%Y") unless record.year.nil? %>
		</td>
		<td class="type">
			<%= record.record_type %>
		</td>
		<td>
		<%= render 'records/own_form' %>
		</td>
</tr>

app/views/records/_stop_owning.html.erb
<%= form_for current_user.reverse_ownership_relationships.find_by_owned_record_id(@record),
             :html => { :method => :delete } do |f| %>
  <div class="actions"><%= f.submit "Remove from collection" %></div>
<% end %>

app/views/records/_track_fields.html.erb
<div>
<%= f.inputs do %>
	<%= f.input :track_number, :as => :select, :collection => 1..25 %>
	<%= f.input :title %>
	<%= f.input :duration, :as => :time,  :label => "Duration (min(s), sec(s))", :include_seconds => true, :discard_hour => true %>
	<%= f.input :bpm, :as => :select, :collection => 65..160 %>
	<%= f.input :playlists %>
	<%= link_to_remove_association "Remove track", f %>
<% end %>
</div>

app/views/records/edit.html.erb
<h1>Edit record</h1>

<%= semantic_form_for(@record) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
	<%= render 'fields', :f => f %>
	<h3>Tracks</h3>
	<div class="tracks">
	<%= f.semantic_fields_for :tracks do |track| %>
		<%= render 'track_fields', :f => track %>
	<% end %>
	<%= link_to_add_association 'Add a track', f, :tracks %>
	</div>
	<%= f.buttons do %>
    <%= f.submit "Update" %>
  <% end %>
<% end %>

app/views/records/index.html.erb
<h1>All records</h1>

<%= will_paginate %>

<% unless @records.empty? %>
  <table index="records_index">
    <tr>
			<th>Artist</th>
			<th>Title</th>
			<th>Year</th>
			<th>Type</th>
			<% if current_user.admin? %>
				<th>Delete?</th>
			<% end %>
		</tr>
		<%= render @records %>
	</table>
<% end %>

<%= will_paginate %>

app/views/records/new.html.erb
<h1>Add a record</h1>

<%= semantic_form_for(@record) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<%= render 'fields', :f => f %>
	<h3>Tracks</h3>
	<%= f.semantic_fields_for :tracks do |track| %>
		<%= render 'track_fields', :f => track %>
	<% end %>
	<%= link_to_add_association 'Add a track', f, :tracks %>
	<%= f.buttons do %>
    <%= f.submit "Update" %>
  <% end %>
<% end %>

app/views/records/show.html.erb
<h3><%= @record.artist + " - " + @record.title %></h3>
<table id="record">
	<tr>
		<td class="col1">Year</td>
		<td>
			<%= @record.year.strftime("%Y") unless @record.year.nil? %>
		</td>
  </tr>
	<tr>
		<td class="col1">Type</td>
		<td>
			<%= @record.record_type %>
		</td>
  </tr>
	<tr>
		<td>
			<%= render 'own_form' %>
		</td>
	</tr>
</table>
<% unless @record.tracks.empty? %>
<table id="tracks">
	<tr>
    <th>Track no</th>
    <th>Title</th>
		<th>Duration</th>
		<th>BPM</th>
		<th>Add to/remove from playlists</th> 
  </tr>
<% for track in @record.tracks %>
		<tr>
			<td class="track_no">
				<%=h track.track_number %>
			</td>
			<td class="track_title">
				<%=h track.title %>
			</td>
			<td class="duration">
				<%=h track.duration.strftime("%M:%S") unless track.duration.nil? %>
			</td>
			<td class="bpm">
				<%=h track.bpm %>
			</td>
			<td>
			<%= semantic_form_for track do |f| %>
				<%= f.input :playlists, :label => false %>
				<%= f.buttons %>
			<% end %>
			</td>
		</tr>
<% end %>
<% end %>
</table>

<%= link_to "Edit record", edit_record_path(@record) %>