config/routes.rb
Djsbestfriend::Application.routes.draw do

	resources :users do
		member do
			get :owned_records
		end
	end
	
	resources :sessions, :only => [:new, :create, :destroy]
	resources :records do
		member do
			get :owners
		end
	end
	
	resources :playlists do
		member do
			get :playlist_tracks
		end
	end
	
	resources :tracks do
		member do
			get :playlists
		end
	end
	
	resources :ownership_relationships, :only => [:create, :destroy]
	resources :playlist_relationships, :only => [:create, :destroy]
	
	match '/signup',  :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

	match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  
  root :to => 'pages#home'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
	attr_accessible :title, :grouping, :duration, :description, :year
	
	has_many :reverse_playlist_relationships, :foreign_key => "playlist_id",
                                   :class_name => "PlaylistRelationship",
                                   :dependent => :destroy
	has_many :playlist_tracks, :through => :reverse_playlist_relationships
	
	def in_playlist?(playlist_track)
		reverse_playlist_relationships.find_by_playlist_track_id(playlist_track)
	end
	
	def add_to_playlist!(playlist_track)
		reverse_playlist_relationships.create!(:playlist_track_id => playlist_track.id)
	end
	
	def remove_from_playlist!(playlist_track)
		reverse_playlist_relationships.find_by_playlist_track_id(playlist_track).destroy
	end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
	
	def new
		@playlist = Playlist.new
	end

	def show
		@playlist = Playlist.find(params[:id])
		@title = @playlist.title
	end
	
	def edit
		@playlist = Playlist.find(params[:id])
		@title = "Edit playlist"
	end
	
	def index
		@playlists = Playlist.paginate(:page => params[:page])
	end
	
	def create
    @playlist = Playlist.new(params[:playlist])
    if @playlist.save
			flash[:success] = "New playlist created!"
      redirect_to root_path
    else
      @title = "Add a new playlist"
      render 'new'
    end
  end
	
	def update
		@playlist = Playlist.find(params[:id])
		if @playlist.update_attributes(params[:playlist])
			flash[:success] = "playlist updated."
			redirect_to @playlist
		else
			@title = "Edit playlist"
			render 'edit'
		end
	end
	
	def destroy
		if signed_in?
			@playlist = Playlist.find(params[:id])
			@playlist.destroy
			flash[:success] = "playlist destroyed."
			redirect_to playlists_path
		else
			flash[:error] = "Please sign in to destroy a playlist."
			redirect_to signin_path
		end
	end
end

app/views/playlists/_fields.html.erb
<%= f.inputs do %>
	<%= f.input :title %>
	<%= f.input :grouping %>
	<%= f.input :year, :as => :date,		 :discard_day => true, :discard_month => true, :start_year => Time.now.year,
																			 :end_year => Time.now.year-10, :include_blank => false  %>
	<%= f.input :description, :input_html => { :class => 'comment' } %>
<% end %>

app/views/playlists/_playlist.html.erb
<tr>
		<td class="title">
		  <%= link_to playlist.title, playlist %>
		</td>
		<td class="year">
			<%= playlist.year.strftime("%Y") unless playlist.year.nil? %>
		</td>
		<td>
			<%= playlist.grouping %>
		</td>
</tr>

app/views/playlists/edit.html.erb
<h1>Edit playlist</h1>

<%= semantic_form_for(@playlist) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
	<%= render 'fields', :f => f %>
	<%= f.buttons do %>
    <%= f.submit "Update" %>
  <% end %>
<% end %>

app/views/playlists/index.html.erb
<h1>All playlists</h1>

<%= will_paginate %>

<% unless @playlists.empty? %>
  <table index="records_index">
    <tr>
			<th>Title</th>
			<th>Duration</th>
			<th>Grouping</th>
			<th>Year</th>
		</tr>
		<%= render @playlists %>
	</table>
<% end %>

<%= will_paginate %>

app/views/playlists/new.html.erb
<h1>Create a playlist</h1>

<%= semantic_form_for(@playlist) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<%= render 'fields', :f => f %>
	<%= f.buttons do %>
		<%= f.submit "Create" %>
  <% end %>
<% end %>

app/views/playlists/show.html.erb
<h2><%= @playlist.title %></h2>
<table id="record">
	<tr>
		<td class="col1">Duration</td>
		<td>
			<%= @playlist.duration %>
		</td>
  </tr>
	<tr>
		<td class="col1">Grouping</td>
		<td>
			<%= @playlist.grouping %>
		</td>
  </tr>
	<tr>
		<td class="col1">Year</td>
		<td>
			<%= @playlist.year.strftime("%Y") unless @playlist.year.nil? %>
		</td>
  </tr>
</table>
<% unless @playlist.playlist_tracks.empty? %>
<table id="tracks">
	<tr>
    <th>Track no</th>
    <th>Title</th>
		<th>Duration</th>
		<th>BPM</th>
  </tr>
<% for playlist_track in @playlist.playlist_tracks %>
		<tr>
			<td class="track_no">
				<%=h playlist_track.track_number %>
			</td>
			<td class="track_title">
				<%=h playlist_track.title %>
			</td>
			<td class="duration">
				<%=h playlist_track.duration.strftime("%M:%S") unless playlist_track.duration.nil? %>
			</td>
			<td class="bpm">
				<%=h playlist_track.bpm %>
			</td>
		</tr>
<% end %>
<% end %>
</table>

<%= link_to "Edit playlist", edit_playlist_path(@playlist) %>